global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
  - targets: ['go-application:5000','python-application:5000','dotnet-application:5000','nodejs-application:5000']